title: Noelia Garcia Weidling
#logo
description: I am a **Data Analytics** and **Information Systems** student at **Utah State University**. Originally from **Bolivia**, I have navigated both cultural and academic challenges, which have shaped my resilience and problem-solving skills.
With expertise in **Python**, **SQL**, **Tableau**, and **AWS**, I have contributed to impactful projects at **ASPIRE ERC**, particularly in **electric roadways** and **electric vehicle charging infrastructure**. My academic and professional experiences have deepened my understanding of **machine learning**, **data analysis**, and **strategic planning**.
My primary interest lies in **data science**, and I am eager to apply my skills to projects that drive innovation and solve real-world problems through data-driven solutions.
#show_downloads: true
theme:jekyll-theme-minimal
