title: Noelia Garcia Weidling
logo: docs/assets/D1F71508-D35C-45A9-84B1-237FAF116D62 2.JPEG
description: Data Analytics and Information Systems student at Utah State University. 
theme: jekyll-theme-minimal
